all: jobExecutor worker

jobExecutor: jobExecutor.o functions.o map.o
	gcc jobExecutor.o functions.o map.o -o jobExecutor

jobExecutor.o: jobExecutor.c
	gcc -c jobExecutor.c

functions.o: functions.c
	gcc -c functions.c

map.o: map.c
	gcc -c map.c

worker: worker.o worker_functions.o map.o
	gcc worker.o worker_functions.o map.o -o worker

worker.o: worker.c
	gcc -c worker.c

worker_functions.o: worker_functions.c
	gcc -c worker_functions.c

map.o: map.c
	gcc -c map.c

clean:
	
rm -rf *.o
	rm -rf jobExecutor
	rm -rf worker
	find .  -maxdepth 1 -type p -delete
